server:
  port: 8081

spring:
  application:
    name: flight-service

  datasource:
    url: jdbc:mysql://localhost:3306/flight-service
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    feign: DEBUG
